#springboot内置配置
server:
  port: 8081
spring:
    datasource:
        name: crmDs
        driver-class-name: oracle.jdbc.driver.OracleDriver
        ##driver-class-name: oracle.jdbc.driver.OracleDriver
        ##url: jdbc:oracle:thin:@192.168.1.191:1521:zhgl
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: futures
        password: abs
        initialSize: 5
        maxActive: 20
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 100
        filters: stat,wall
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.winter.model  # 注意：对应实体类的路径